### ISSUE TITLE
Error: TypeError (no implicit conversion of Integer into String)

### ISSUE THREAD

**Issue by jroodman** [sidoh/alexa_verifier#1]
Verifier is failing to correctly convert Unix time to a Ruby Time object. 

Fix: 
    Change: Time.parse(request_json['request']['timestamp']) 
            - on line 69 of alexa_verifier/lib/alexa_verifier.rb 
    To: Time.at(request_json['request']['timestamp'])

**Comment by sidoh** [comment]
Nice, thanks for catching that.

I might recommend coercing the value into a string so that it supports either string or int inputs, eg:

```ruby
Time.parse(request_json['request']['timestamp'].to_s)
```

Did you want to open a PR?

**Comment by jroodman** [comment]
Yeah, I definitely agree on handling both. Digging into it more I found that the requests were switching between sending unix time and a string version of UTC time. So idk whats up with Alexa lol. 

Not sure to_s will work with unix time though. The Ruby docs are a little vague, but seem to imply it won't. I can do a fix with an if/then based on class type that may work well though.

**Comment by sidoh** [comment]
Oh I misunderstood what you meant by string. I thought it was just `"1500146159"` or whatever. Pretty wild it differs in that way.

Checking based on type makes sense. Might consider making it robust to the case I was assuming (unix timestamp formatted as a string). Doesn't seem like one can rely on Amazon to be consistent :)

**Comment by jroodman** [comment]
I think UNIX time should be standard now. 

The UTC timestamp seems to only be occurring via Amazon's simulated requests for testing. They added a warning that the system is now working properly a couple days ago.

**Comment by mattrayner** [comment]
@jroodman this is fixed in #2
